"""migrate.py — migrate three-pillars repos from the legacy docs/tdd-* layout to three-pillars-docs/tp-*.

Stages:
- detect(): build a migration plan describing required moves and rewrites.
- --dry-run: print the plan, exit 0, no FS mutation.        [Task 3.2]
- --apply: execute moves (Task 3.3) and rewrites (Task 3.4), atomic. [Task 3.5+]

The plan output is sorted so it can be diffed against hand-authored fixtures.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import tempfile
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path


MIGRATION_COMMIT_MESSAGE = (
    "Migrate: legacy docs/tdd-* layout to three-pillars-docs/tp-*\n"
    "\n"
    "Auto-generated by skills/_shared/migrate.py --apply."
)

MEMORY_MD_ADVISORY = (
    "MEMORY.md and user-level CLAUDE.md may reference old tdd-* skill names — review manually."
)

LAST_DESIGN_ADVISORY = (
    ".claude/last-design references active designs at the old path — "
    "re-check via /tp-session-restore"
)


class MigrationError(Exception):
    """Raised when the migration cannot proceed (e.g., dirty repo)."""


EXCLUDED_DIRS = frozenset({
    ".git",
    "__pycache__",
    "node_modules",
    ".three-pillars",
    "three-pillars-docs",
    # `fixtures` (anywhere in the tree) holds migration-tool test inputs that
    # intentionally embed legacy patterns. Rewriting them destroys the test
    # corpus and breaks every subsequent migrate.py invocation.
    "fixtures",
})

# Files that intentionally document or detect legacy patterns and would lose
# their meaning if rewritten. Paths are relative to repo root, posix style.
DO_NOT_REWRITE_FILES = frozenset({
    # Documents what migrate.py LOOKS FOR — rewriting inverts the trigger
    # description (it would say "trigger on three-pillars-docs/tp-designs/",
    # which is the opposite of correct).
    "skills/_shared/first-run.md",
})


# The `(?<![a-z-])` lookbehind on every `docs/...` match is load-bearing: without
# it, `docs/vision.md` matches the suffix of `three-pillars-docs/vision.md`, so
# detect() falsely flags already-migrated files and apply() corrupts them by
# rewriting `three-pillars-docs/` → `three-pillars-three-pillars-docs/`.
_OLD_PATTERN = re.compile(
    r"(?<![a-z-])docs/(?:tdd-designs|completed-tdd-designs|vision\.md|architecture\.md|product_roadmap\.md|known_issues\.md)"
    r"|/tdd-(?:design|spike|plan|phase|task|session|docs|setup|test|implementation|guide)"
    r"|\btdd-(?:design|spike|plan|phase|task|session|docs|setup|test|implementation|guide)\b"
    r"|\btdd/[a-z][a-z0-9-]*"
)


_SKILL_NAME_ALTERNATION = r"design|spike|plan|phase|task|session|docs|setup|test|implementation|guide"
# Rewriter uses the same (?<![a-z-]) lookbehind as the detector so idempotency
# holds — running migrate.py twice on the same file is a no-op, and a file that
# already references `three-pillars-docs/...` is left untouched.
_PATH_REGEX_REPLACEMENTS = (
    (re.compile(r"(?<![a-z-])docs/tdd-designs/"), "three-pillars-docs/tp-designs/"),
    (re.compile(r"(?<![a-z-])docs/completed-tdd-designs/"), "three-pillars-docs/completed-tp-designs/"),
    (re.compile(r"(?<![a-z-])docs/vision\.md"), "three-pillars-docs/vision.md"),
    (re.compile(r"(?<![a-z-])docs/architecture\.md"), "three-pillars-docs/architecture.md"),
    (re.compile(r"(?<![a-z-])docs/product_roadmap\.md"), "three-pillars-docs/product_roadmap.md"),
    (re.compile(r"(?<![a-z-])docs/known_issues\.md"), "three-pillars-docs/known_issues.md"),
)
_SLASH_SKILL_REGEX = re.compile(rf"/tdd-(?=(?:{_SKILL_NAME_ALTERNATION})\b)")
_BARE_SKILL_REGEX = re.compile(rf"\btdd-(?=(?:{_SKILL_NAME_ALTERNATION})\b)")
_BRANCH_REGEX = re.compile(r"\btdd/(?=[a-z][a-z0-9-]*)")


@dataclass
class MigrationPlan:
    moves: list[tuple[str, str]] = field(default_factory=list)
    rewrites: list[str] = field(default_factory=list)
    already_migrated: bool = False

    def to_dict(self) -> dict:
        return {
            "moves": [[s, d] for s, d in self.moves],
            "rewrites": list(self.rewrites),
        }

    def is_empty(self) -> bool:
        return not self.moves and not self.rewrites


CONFIG_RELATIVE_PATH = ".three-pillars/config.json"


def _read_config(repo: Path) -> dict | None:
    """Read .three-pillars/config.json if present. Fail-open: returns None on missing/corrupt."""
    config_path = repo / CONFIG_RELATIVE_PATH
    if not config_path.is_file():
        return None
    try:
        return json.loads(config_path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return None


def _is_migrated(repo: Path) -> bool:
    config = _read_config(repo)
    if not config:
        return False
    return bool(config.get("migration", {}).get("completed_at"))


def _write_config_completed(repo: Path) -> None:
    """Atomically set migration.completed_at and migration.from_layout in .three-pillars/config.json.

    Creates the file if missing. Preserves other top-level keys. Uses tmp-in-same-dir
    + os.replace per skills/_shared/repo-config.md.
    """
    config_path = repo / CONFIG_RELATIVE_PATH
    config_path.parent.mkdir(parents=True, exist_ok=True)

    if config_path.is_file():
        try:
            config = json.loads(config_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            raise MigrationError(
                f"{CONFIG_RELATIVE_PATH} exists but does not parse as JSON; "
                "refusing to overwrite. Inspect the file before re-running."
            ) from exc
    else:
        config = {}

    config.setdefault("schema_version", 1)
    migration = config.setdefault("migration", {})
    migration["completed_at"] = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    migration["from_layout"] = "docs+tdd"

    tmp = tempfile.NamedTemporaryFile(
        mode="w",
        dir=config_path.parent,
        prefix=".config.",
        suffix=".tmp",
        delete=False,
        encoding="utf-8",
    )
    try:
        json.dump(config, tmp, indent=2)
        tmp.write("\n")
        tmp.flush()
        os.fsync(tmp.fileno())
        tmp.close()
        os.replace(tmp.name, config_path)
    except Exception:
        tmp.close()
        try:
            os.unlink(tmp.name)
        except OSError:
            pass
        raise


def _collect_moves(repo_path: Path) -> list[tuple[str, str]]:
    moves: list[tuple[str, str]] = []

    for name in ("vision.md", "architecture.md", "product_roadmap.md", "known_issues.md"):
        src = repo_path / "docs" / name
        if src.is_file():
            moves.append((f"docs/{name}", f"three-pillars-docs/{name}"))

    designs_root = repo_path / "docs" / "tdd-designs"
    if designs_root.is_dir():
        for p in designs_root.rglob("*"):
            if p.is_file():
                rel = p.relative_to(repo_path).as_posix()
                dst = rel.replace("docs/tdd-designs/", "three-pillars-docs/tp-designs/", 1)
                moves.append((rel, dst))

    completed_root = repo_path / "docs" / "completed-tdd-designs"
    if completed_root.is_dir():
        for p in completed_root.rglob("*"):
            if p.is_file():
                rel = p.relative_to(repo_path).as_posix()
                dst = rel.replace(
                    "docs/completed-tdd-designs/",
                    "three-pillars-docs/completed-tp-designs/",
                    1,
                )
                moves.append((rel, dst))

    return sorted(moves)


def _is_excluded(rel_parts: tuple[str, ...]) -> bool:
    for part in rel_parts[:-1]:
        if part in EXCLUDED_DIRS or part.startswith("."):
            return True
    return False


def _collect_rewrites(repo_path: Path) -> list[str]:
    rewrites: list[str] = []
    for path in repo_path.rglob("*.md"):
        rel = path.relative_to(repo_path)
        if _is_excluded(rel.parts):
            continue
        rel_posix = rel.as_posix()
        if rel_posix in DO_NOT_REWRITE_FILES:
            continue
        try:
            content = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        if _OLD_PATTERN.search(content):
            rewrites.append(rel_posix)
    return sorted(rewrites)


def detect(repo_path: Path | str) -> MigrationPlan:
    """Build a MigrationPlan describing required moves and rewrites.

    Idempotent: if .three-pillars/config.json records migration.completed_at,
    returns a plan flagged as already_migrated with no work — regardless of
    whether stale legacy paths happen to still exist.

    Otherwise, the old layout is detected by the presence of any of:
      - docs/vision.md
      - docs/tdd-designs/
      - docs/completed-tdd-designs/

    Moves and rewrites are collected independently: a repo whose filesystem
    has already been hand-migrated (no path markers) but whose text content
    still references `/tdd-*` skill names is a *partial-migration* state, and
    apply() must be able to clean up the stragglers. The plan is empty only
    when both moves and rewrites are empty.
    """
    repo = Path(repo_path)
    if _is_migrated(repo):
        return MigrationPlan(already_migrated=True)
    moves = _collect_moves(repo)
    rewrites = _collect_rewrites(repo)
    return MigrationPlan(moves=moves, rewrites=rewrites)


def _rewrite_content(text: str) -> str:
    """Apply the migration's pattern substitutions to a string.

    Order:
      1. Path replacements (docs/{vision,...}.md, docs/{tdd-designs,completed-tdd-designs}/).
      2. Slash-prefixed skill names (/tdd-{skill} -> /tp-{skill}).
      3. Bare skill names (tdd-{skill} -> tp-{skill}).
      4. Branch refs (tdd/{name} -> tp/{name}).

    Skill-name and branch substitutions use lookahead to confirm the suffix is
    a known skill or a valid branch slug before rewriting. Idempotent: running
    the function on its own output is a no-op.
    """
    for regex, replacement in _PATH_REGEX_REPLACEMENTS:
        text = regex.sub(replacement, text)
    text = _SLASH_SKILL_REGEX.sub("/tp-", text)
    text = _BARE_SKILL_REGEX.sub("tp-", text)
    text = _BRANCH_REGEX.sub("tp/", text)
    return text


def _rewrite_file(path: Path) -> bool:
    """Rewrite a file in place using atomic tmp+rename. Returns True iff content changed."""
    original = path.read_text(encoding="utf-8")
    updated = _rewrite_content(original)
    if updated == original:
        return False
    tmp = path.with_name(path.name + ".tmp.migrate")
    tmp.write_text(updated, encoding="utf-8")
    tmp.replace(path)
    return True


def _run_git(args: list[str], cwd: Path, check: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", *args], cwd=cwd, capture_output=True, text=True, check=check
    )


def _ensure_clean_repo(repo: Path) -> None:
    status = _run_git(["status", "--porcelain"], cwd=repo).stdout
    if status.strip():
        raise MigrationError(
            "repo has uncommitted changes; commit or stash before --apply:\n" + status
        )


def _git_mv(src: str, dst: str, repo: Path) -> None:
    (repo / dst).parent.mkdir(parents=True, exist_ok=True)
    _run_git(["mv", src, dst], cwd=repo)


def _prune_empty_dirs(repo: Path, srcs: list[str]) -> None:
    """After moves complete, remove src parent directories that are now empty.

    `git mv` removes the file but not its parent dir; without this pass, an
    otherwise-fully-migrated repo would still have an empty `docs/` tree.
    """
    for src in srcs:
        parent = (repo / src).parent
        while parent != repo and parent.is_dir():
            try:
                parent.rmdir()
            except OSError:
                break
            parent = parent.parent


def _rollback_moves(repo: Path, completed: list[tuple[str, str]]) -> None:
    """Restore the repo to its pre-apply state.

    Per spec: `git restore --staged .` + `git checkout -- .`. That returns the
    index and tracked working tree to HEAD, but leaves the dst files we created
    as untracked detritus, so we also remove each dst file and any parent
    directory that we created and is now empty.
    """
    _run_git(["restore", "--staged", "."], cwd=repo, check=False)
    _run_git(["checkout", "--", "."], cwd=repo, check=False)
    for _src, dst in completed:
        dst_path = repo / dst
        if dst_path.is_file():
            dst_path.unlink()
    for _src, dst in completed:
        parent = (repo / dst).parent
        while parent != repo and parent.is_dir():
            try:
                parent.rmdir()
            except OSError:
                break
            parent = parent.parent


def apply(repo: Path, plan: MigrationPlan) -> int:
    """Execute moves and rewrites in one staged-then-committed transaction.

    Returns 0 on success or already-migrated short-circuit. On any failure mid-
    apply, rolls back to pre-apply state and returns a non-zero code.
    """
    if plan.already_migrated:
        sys.stdout.write(
            "migrate.py: repo is already migrated "
            "(.three-pillars/config.json records migration.completed_at); nothing to do.\n"
        )
        return 0
    if plan.is_empty():
        return 0

    try:
        _ensure_clean_repo(repo)
    except MigrationError as exc:
        sys.stderr.write(f"migrate.py: {exc}\n")
        return 2

    completed_moves: list[tuple[str, str]] = []
    try:
        for rel_path in plan.rewrites:
            changed = _rewrite_file(repo / rel_path)
            if changed:
                _run_git(["add", "--", rel_path], cwd=repo)
        for src, dst in plan.moves:
            _git_mv(src, dst, repo)
            completed_moves.append((src, dst))
        _prune_empty_dirs(repo, [src for src, _ in completed_moves])
        _write_config_completed(repo)
        _run_git(["add", "--", CONFIG_RELATIVE_PATH], cwd=repo)
        _run_git(["commit", "--quiet", "-m", MIGRATION_COMMIT_MESSAGE], cwd=repo)
        sys.stdout.write(MEMORY_MD_ADVISORY + "\n")
        # .claude/last-design holds an MRU of design names (leaf folder names),
        # not paths — entries remain valid post-migration. The advisory is
        # purely a "you may want to re-verify" nudge; the file is never
        # rewritten. Print only when the file exists so absent-file runs stay
        # quiet (verified by test_apply_silent_when_claude_last_design_absent).
        if (repo / ".claude" / "last-design").is_file():
            sys.stdout.write(LAST_DESIGN_ADVISORY + "\n")
        return 0
    except subprocess.CalledProcessError as exc:
        sys.stderr.write(
            f"migrate.py: --apply failed mid-flight, rolling back ({exc.cmd}): "
            f"{exc.stderr or exc.stdout or ''}\n"
        )
        _rollback_moves(repo, completed_moves)
        return 1
    except MigrationError as exc:
        sys.stderr.write(f"migrate.py: {exc}\n")
        _rollback_moves(repo, completed_moves)
        return 1


def format_plan(plan: MigrationPlan) -> str:
    """Render the plan as a deterministic, diff-stable string for --dry-run output.

    Format is intentionally machine-comparable: sorted lists, ASCII arrows, no
    absolute paths or timestamps. Hand-authored fixtures can be byte-compared.
    """
    if plan.already_migrated:
        return (
            "Migration plan (dry-run, no changes made):\n\n"
            "Repo is already migrated (.three-pillars/config.json records migration.completed_at); "
            "nothing to do.\n"
        )
    if plan.is_empty():
        return "Migration plan (dry-run, no changes made):\n\nRepo is already on the current layout — nothing to migrate.\n"

    lines: list[str] = ["Migration plan (dry-run, no changes made):", ""]

    lines.append(f"Moves ({len(plan.moves)}):")
    for src, dst in plan.moves:
        lines.append(f"  {src} -> {dst}")
    lines.append("")

    lines.append(f"Rewrites ({len(plan.rewrites)}):")
    for path in plan.rewrites:
        lines.append(f"  {path}")
    lines.append("")

    lines.append("Run with --apply to execute.")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="migrate.py",
        description="Migrate a three-pillars repo from the legacy docs/tdd-* layout to three-pillars-docs/tp-*.",
    )
    parser.add_argument(
        "--repo",
        default=".",
        help="Path to the repo root (default: current directory).",
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the migration plan and exit without touching the filesystem (default mode).",
    )
    mode.add_argument(
        "--apply",
        action="store_true",
        help="Execute the migration plan: move files and rewrite references.",
    )

    args = parser.parse_args(argv)

    repo = Path(args.repo).resolve()
    if not repo.is_dir():
        print(f"error: --repo path is not a directory: {repo}", file=sys.stderr)
        return 2

    plan = detect(repo)

    if args.apply:
        return apply(repo, plan)

    sys.stdout.write(format_plan(plan))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
